defaults:
  - submitit_slurm

submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 3600
cpus_per_task: 16
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 64
nodes: 1
name: ${hydra.job.name}d
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: 'gpu-l40s'
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
account: weirdlab
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
